# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b7a376e261fce17f23fe20db1496fc423a7333a3da28f47383cefc9f8748bd064fb00d09ac2d24ba2ebe10c68d0f42b46e700ce51cb9d15d121d2ff23c867ad

test:
  secret_key_base: b47f88c7fd588a42b0373e0d8531d145130732dc009802130faa172b96e9035525d105d58de62d1ff55325d1da4d105b506cc665fd48eff05df0580c3d1c4896

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
